/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as SuppliersAddRouteImport } from './routes/suppliers.add'
import { Route as OrdersNewRouteImport } from './routes/orders/new'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as LocationsLocationIdItemsRouteImport } from './routes/locations/$locationId.items'

const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersAddRoute = SuppliersAddRouteImport.update({
  id: '/suppliers/add',
  path: '/suppliers/add',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIdItemsRoute =
  LocationsLocationIdItemsRouteImport.update({
    id: '/locations/$locationId/items',
    path: '/locations/$locationId/items',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/receive': typeof ReceiveRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/suppliers/add': typeof SuppliersAddRoute
  '/inventory': typeof InventoryIndexRoute
  '/items': typeof ItemsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/locations/$locationId/items': typeof LocationsLocationIdItemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/receive': typeof ReceiveRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/suppliers/add': typeof SuppliersAddRoute
  '/inventory': typeof InventoryIndexRoute
  '/items': typeof ItemsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/locations/$locationId/items': typeof LocationsLocationIdItemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/receive': typeof ReceiveRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/suppliers/add': typeof SuppliersAddRoute
  '/inventory/': typeof InventoryIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/locations/$locationId/items': typeof LocationsLocationIdItemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/receive'
    | '/orders/$orderId'
    | '/orders/new'
    | '/suppliers/add'
    | '/inventory'
    | '/items'
    | '/locations'
    | '/orders'
    | '/locations/$locationId/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/receive'
    | '/orders/$orderId'
    | '/orders/new'
    | '/suppliers/add'
    | '/inventory'
    | '/items'
    | '/locations'
    | '/orders'
    | '/locations/$locationId/items'
  id:
    | '__root__'
    | '/'
    | '/receive'
    | '/orders/$orderId'
    | '/orders/new'
    | '/suppliers/add'
    | '/inventory/'
    | '/items/'
    | '/locations/'
    | '/orders/'
    | '/locations/$locationId/items'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReceiveRoute: typeof ReceiveRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  SuppliersAddRoute: typeof SuppliersAddRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  LocationsLocationIdItemsRoute: typeof LocationsLocationIdItemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/add': {
      id: '/suppliers/add'
      path: '/suppliers/add'
      fullPath: '/suppliers/add'
      preLoaderRoute: typeof SuppliersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$locationId/items': {
      id: '/locations/$locationId/items'
      path: '/locations/$locationId/items'
      fullPath: '/locations/$locationId/items'
      preLoaderRoute: typeof LocationsLocationIdItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReceiveRoute: ReceiveRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  SuppliersAddRoute: SuppliersAddRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  LocationsLocationIdItemsRoute: LocationsLocationIdItemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
